// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn7DH8vyV-V_durgsGw0kDaygpZYXLZro',
    appId: '1:760429122118:web:257825969238763c1f7047',
    messagingSenderId: '760429122118',
    projectId: 'dompetku-apps',
    authDomain: 'dompetku-apps.firebaseapp.com',
    storageBucket: 'dompetku-apps.firebasestorage.app',
    measurementId: 'G-W1MHGJD7KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjrSf-vYLZG-HcQCvR1Vd1o-nQRCGjKs0',
    appId: '1:760429122118:android:2a49fdfa1fde41531f7047',
    messagingSenderId: '760429122118',
    projectId: 'dompetku-apps',
    storageBucket: 'dompetku-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2tMSZHBI0GK8edb57GJ72iLPlNjs-hI',
    appId: '1:760429122118:ios:79e1b50fa3f258ad1f7047',
    messagingSenderId: '760429122118',
    projectId: 'dompetku-apps',
    storageBucket: 'dompetku-apps.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2tMSZHBI0GK8edb57GJ72iLPlNjs-hI',
    appId: '1:760429122118:ios:79e1b50fa3f258ad1f7047',
    messagingSenderId: '760429122118',
    projectId: 'dompetku-apps',
    storageBucket: 'dompetku-apps.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn7DH8vyV-V_durgsGw0kDaygpZYXLZro',
    appId: '1:760429122118:web:f7ba78f256d21d3c1f7047',
    messagingSenderId: '760429122118',
    projectId: 'dompetku-apps',
    authDomain: 'dompetku-apps.firebaseapp.com',
    storageBucket: 'dompetku-apps.firebasestorage.app',
    measurementId: 'G-T58JNYHVVD',
  );
}
